<li class="">
                                            <a href="[field:arcurl/]">
                                                <img src="[field:picname/]" width="268" height="204">
                                                <div class="be"></div>
                                                <div class="te">
                                                    <h1>[field:title/]</h1>
                                                    <p style="text-indent:2em;">[field:description function="cn_substr(@me,100)"/]...</p>
                                                </div>
                                            </a>
                                        </li>