<div class="th-[field:global.autoindex/]" id="course-[field:global.autoindex/]" style="background-image:url([field:picname/])">
                                <div class="fright">
                                    
                                        <i>[field:zdy/]</i>
                                    
                                        <i>[field:zde/]</i>
                                    
                                        <i>[field:zds/]</i>
                                    
                                    <div class="cls">&nbsp;</div>
                                    <p class="em">[field:zdsi/]</p>
                                </div>
                            </div>