<div class="th-1" id="course-1" style="background-image:url([field:picname/])">
                                <div class="fright">
                                    
                                        <i>[field:picname/]</i>
                                    
                                        <i>勇敢</i>
                                    
                                        <i>领导力</i>
                                    
                                    <div class="cls">&nbsp;</div>
                                    <p class="em">本课程是为培养3-8岁孩子未来领导力而专门设计的课程，使其具备领导者必备的领导力和竞争力，为日后发展奠定坚实的基础。</p>
                                </div>
                            </div>