
<field:nj itemname="孩子所读年级" autofield="1" type="select" isnull="true" default="小班,中班,大班,1年级,2年级,3年级,4年级,5年级,6年级"  maxlength="250" page="">
</field:nj>



<field:dt itemname="孩子动态" autofield="1" type="checkbox" isnull="true" default="学习能力与方法欠佳、成绩不稳定、自信心不强,学习主动性不够、不愿动脑筋、有畏难情绪,记忆力不强、学习新的忘了,粗心大意、计算易出错、应用题不会思考,阅读理解有困难、语言表达能力不足、写作欠佳,上课注意力不够集中、易分心、小动作多"  maxlength="250" page="">
</field:dt>


<field:yq itemname="家长要求" autofield="1" type="checkbox" isnull="true" default="希望改进学习方法和提高学习成绩,希望提高做作业的速度与质量,希望培养听、说、读、写、算、思考等学习能力,希望培养孩子独立能力、增加自信心,希望加强孩子学习时的注意力,希望规范孩子的行为习惯"  maxlength="250" page="">
</field:yq>


<field:name itemname="孩子姓名" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:name>

<field:jname itemname="家长姓名" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:jname>

<field:phone itemname="家长手机" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:phone>

<field:xq itemname="附近校区" autofield="1" type="select" isnull="true" default="广州体育西校区,广州东山汇校区,广州海珠校区,广州陈家祠校区,广州东风东校区,北京长安校区,上海静安校区,深圳世纪汇校区"  maxlength="250" page="">
</field:xq>


<field:sj itemname="预约时间" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:sj>
