
<field:nj itemname="孩子所读年级" autofield="1" type="select" isnull="true" default="年级"  maxlength="250" page="">
</field:nj>

<field:dt itemname="孩子动态" autofield="1" type="checkbox" isnull="true" default="动态"  maxlength="250" page="">
</field:dt>

<field:yq itemname="家长要求" autofield="1" type="checkbox" isnull="true" default="要求"  maxlength="250" page="">
</field:yq>

<field:name itemname="孩子姓名" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:name>

<field:jname itemname="家长姓名" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:jname>

<field:phone itemname="家长手机" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:phone>

<field:xq itemname="附近校区" autofield="1" type="select" isnull="true" default="校区"  maxlength="250" page="">
</field:xq>

<field:sj itemname="预约时间" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:sj>
