<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="1";
$z[1]=Array("img"," /uploads/allimg/160812/1-160Q2143106.jpg ",93,240);
$z[1][4]['ddimg']="/uploads/allimg/160812/1-160Q2143106.jpg";
$z[1][4]['text']="on";
$z[1][4]['width']="550";
$z[1][4]['height']="390";
$z[2]=Array("img"," /uploads/allimg/160812/1-160Q2143112.jpg ",242,387);
$z[2][4]['ddimg']="/uploads/allimg/160812/1-160Q2143112.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="550";
$z[2][4]['height']="414";
$z[3]=Array("img"," /uploads/allimg/160812/1-160Q2143117.jpg ",389,534);
$z[3][4]['ddimg']="/uploads/allimg/160812/1-160Q2143117.jpg";
$z[3][4]['text']="";
$z[3][4]['width']="550";
$z[3][4]['height']="272";

?>