<div class="channel" style="border:none">
                            <div class="c_left">
                                <a target="_blank" href="{dede:field name='typeurl'/}">
                                    <h1>{dede:field name='typename'/}</h1>
                                    
                                        <img src="{dede:field name='typepic'/}" width="273" height="166">
                                    
                                </a>
                            </div>
                            <div class="c_right" style="border:none; width:527px;">
                                <h1 style="color:#7da42b">{dede:field name='typetitle'/}</h1>
                                <ul class="shuo">

                                    
                                    

                                    {dede:arclist    row='5'   titlelen='40'}
                                        <li>
                                            <a target="_blank" href="[field:arcurl/]">[field:title/]</a>
                                        </li>
                                    {/dede:arclist}
                                      
                                       
                                    
                                    


                                    <div class="more">
                                        <a target="_blank" href="{dede:field name='typeurl'/}">
                                            <img src="/assets/static/images/more5.png"></a>
                                    </div>
                                </ul>
                            </div>
                        </div>