<?php
$z[0]=Array("field","",150,178);
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",222,251);
$z[1][4]['name']="typename";
$z[2]=Array("field","",346,374);
$z[2][4]['name']="typepic";
$z[3]=Array("field","",658,688);
$z[3][4]['name']="typetitle";
$z[4]=Array("arclist","\r\n                                        <li>\r\n                                            <a target=\"_blank\" href=\"[field:arcurl/]\">[field:title/]</a>\r\n                                        </li>\r\n                                    ",862,1155);
$z[4][4]['row']="5";
$z[4][4]['titlelen']="40";
$z[5]=Array("field","",1439,1467);
$z[5][4]['name']="typeurl";

?>