<?php
$z[0]=Array("arclist","\r\n					<b><img src=\"[field:picname/]\" width=\"108\" height=\"104\"/></b>\r\n					<p>[field:title/]</p>\r\n                    ",87,277);
$z[0][4]['row']="1";
$z[0][4]['typeid']="23";
$z[1]=Array("channel","\r\n                            <a href=\"[field:typelink/]\" target=\"_blank\">[field:typename/]</a>\r\n                        ",368,553);
$z[1][4]['type']="top";
$z[2]=Array("arclist","\r\n							\r\n							<li>\r\n								<a href=\"[field:arcurl/]\" target=\"_blank\">\r\n									<img src=\"[field:picname/]\" height=\"20\">\r\n									<i></i>\r\n								</a>\r\n							</li>\r\n                        \r\n						",757,1035);
$z[2][4]['row']="20";
$z[2][4]['typeid']="21";
$z[3]=Array("sql","[field:content/]",1261,1349);
$z[3][4]['sql']="Select content from dede_arctype where id=22";

?>