<?php
$z[0]=Array("arclist","\r\n            <a href=\"/\">\r\n                \r\n                \r\n                <img src=\"[field:picname/]\" width=\"445\" height=\"51\"/>\r\n            </a>",65,288);
$z[0][4]['typeid']="24";
$z[0][4]['row']="1";
$z[1]=Array("arclist","\r\n			<span class=\"telnum\">\r\n				<img src=\"[field:picname/]\" width=\"199\" height=\"26\"/>\r\n			</span>",4108,4277);
$z[1][4]['typeid']="25";
$z[1][4]['row']="1";

?>