<?php
$z[0]=Array("field","",268,297);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",335,394);
$z[1][4]['name']="description";
$z[1][4]['function']="html2text(@me)";
$z[2]=Array("field","",745,764);
$z[2][4]['name']="title";
$z[3]=Array("global","",765,791);
$z[3][4]['name']="cfg_webname";
$z[4]=Array("include","",2121,2156);
$z[4][4]['filename']="side.htm";
$z[5]=Array("include","",2197,2232);
$z[5][4]['filename']="head.htm";
$z[6]=Array("field","",2350,2371);
$z[6][4]['name']="typeimg";
$z[7]=Array("include","",2466,2500);
$z[7][4]['filename']="nav.htm";
$z[8]=Array("field","",2895,2924);
$z[8][4]['name']="position";
$z[9]=Array("channel","\r\n                                <li class=\"\">\r\n                                    \r\n                                    <a href=\"[field:typelink/]\">[field:typename/]</a>\r\n                                </li>\r\n                            \r\n                              ",3583,3996);
$z[9][4]['type']="son";
$z[9][4]['currentstyle']="<li class='hover'><a href='~typelink~'>~typename~</a> </li>";

?>