<?php
$z[0]=Array("field","",262,291);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",329,388);
$z[1][4]['name']="description";
$z[1][4]['function']="html2text(@me)";
$z[2]=Array("field","",739,758);
$z[2][4]['name']="title";
$z[3]=Array("global","",759,785);
$z[3][4]['name']="cfg_webname";
$z[4]=Array("include","",2018,2053);
$z[4][4]['filename']="side.htm";
$z[5]=Array("include","",2092,2127);
$z[5][4]['filename']="head.htm";
$z[6]=Array("field","",2245,2266);
$z[6][4]['name']="typeimg";
$z[7]=Array("include","",2361,2395);
$z[7][4]['filename']="nav.htm";
$z[8]=Array("field","",2732,2761);
$z[8][4]['name']="position";
$z[9]=Array("field","",3071,3093);
$z[9][4]['name']="typename";
$z[10]=Array("arclist","\r\n                                        <li>\r\n                                            <div class=\"lipic\">\r\n                                                <img src=\"[field:picname/]\"/>\r\n                                            </div>\r\n                                            <p>[field:title/]</p>\r\n                                        </li>\r\n                                    ",3346,3828);
$z[10][4]['typeid']="28";
$z[10][4]['row']="40";
$z[10][4]['titlelen']="60";
$z[11]=Array("arclist","\r\n                                        <li>\r\n                                            <img src=\"[field:picname/]\"/>\r\n                                        </li>\r\n                                     ",4272,4567);
$z[11][4]['typeid']="28";
$z[11][4]['row']="40";
$z[11][4]['titlelen']="60";
$z[12]=Array("include","",5043,5080);
$z[12][4]['filename']="footer.htm";

?>